In [1]:
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
import gc
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from torch.utils.data import Dataset, DataLoader
import matplotlib as mpl
from collections import OrderedDict
sys.path.append('../.')

# Import only what's actually needed to avoid the dask import issue
from GrindingData import GrindingData
from MyDataset import project_dir
from MyModels import GrindingPredictor
from GrindingData import GrindingData
from MyDataset import project_dir, allowed_input_types, get_dataset, get_collate_fn
device = 'cpu'
CHECKPOINT_DIR = os.path.join("../lfs","checkpoints")

In [2]:
folds=10
repeat=10
for _input_type in allowed_input_types[:-1]:
    for i in range(int(folds*repeat)):
        checkpoint_path = f"{_input_type}_fold{i}_of_folds{folds}.pt"
        checkpoint_path = os.path.join(CHECKPOINT_DIR, checkpoint_path)
# _input_type = allowed_input_types[0]
_input_type = 'all'
_input_type

'all'

In [3]:
folds=10
repeat=10
checkpoint_path = f"{_input_type}_fold{0}_of_folds{folds}.pt"
checkpoint_path = os.path.join(CHECKPOINT_DIR, checkpoint_path)

dataset = get_dataset(input_type=_input_type)
collate_fn = get_collate_fn(input_type=_input_type)
loader = DataLoader(dataset, batch_size=3, shuffle=False, num_workers=0, collate_fn=collate_fn)
model = GrindingPredictor(input_type=_input_type, interp=False)
model.to(device)
checkpoint = torch.load(checkpoint_path, map_location=device)
_state_dict = checkpoint['model_state']
model.load_state_dict(_state_dict, strict=True)

Required components: {'all'}


<All keys matched successfully>

In [3]:
folds=10
repeat=10
for _input_type in allowed_input_types[:-1]:
    for i in range(int(folds*repeat))[:1]:
        checkpoint_path = f"{_input_type}_fold{i}_of_folds{folds}.pt"
        checkpoint_path = os.path.join(CHECKPOINT_DIR, checkpoint_path)

        dataset = get_dataset(input_type=_input_type)
        collate_fn = get_collate_fn(input_type=_input_type)
        loader = DataLoader(dataset, batch_size=3, shuffle=False, num_workers=0, collate_fn=collate_fn)
        model = GrindingPredictor(input_type=_input_type, interp=False)
        model.to(device)
        checkpoint = torch.load(checkpoint_path, map_location=device)
        _state_dict = checkpoint['model_state']
        model.load_state_dict(_state_dict, strict=True)

Required components: {'ae_spec'}
Required components: {'vib_spec'}
Required components: {'ae_features'}
Required components: {'vib_features'}
Required components: {'ae_spec', 'ae_features'}
Required components: {'vib_spec', 'vib_features'}
Required components: {'vib_spec', 'ae_spec', 'ae_features', 'vib_features'}
Required components: {'pp', 'ae_features'}
Required components: {'pp', 'vib_features'}
Required components: {'pp'}
Required components: {'vib_spec', 'ae_spec'}


FileNotFoundError: [Errno 2] No such file or directory: '../lfs/checkpoints/ae_spec+vib_spec_fold0_of_folds10.pt'

In [ ]:
checkpoint = torch.load(checkpoint_path, map_location=device)
_state_dict = checkpoint['model_state']
model.load_state_dict(_state_dict, strict=False)

RuntimeError: Error(s) in loading state_dict for GrindingPredictor:
	size mismatch for regressor.0.weight: copying a param with shape torch.Size([128, 64]) from checkpoint, the shape in current model is torch.Size([128, 192]).

In [8]:
batch = next(iter(loader))
inputs = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in batch.items()}
labels = batch['label'].to(device)
pred = model.forward(inputs)
pred, labels

(tensor([[34.3949],
         [33.2866],
         [33.1813]], grad_fn=<AddmmBackward0>),
 tensor([112, 112, 105]))

(tensor([[34.3949],
         [33.2866],
         [33.1813]], grad_fn=<AddmmBackward0>),
 tensor([112, 112, 105]))

In [17]:
checkpoint['model_state']

OrderedDict([('ae_spec_processor.conv.0.weight',
              tensor([[[[ 1.8810e-01,  9.7475e-02, -4.0856e-02],
                        [ 2.0492e-01,  1.7017e-01,  1.7988e-02],
                        [ 4.0255e-02, -1.3628e-01, -3.5494e-01]],
              
                       [[-1.0835e-01,  7.8401e-02,  8.1748e-02],
                        [ 9.1444e-02, -8.1134e-02, -1.8812e-01],
                        [-1.9436e-01,  4.1149e-02, -1.1562e-01]]],
              
              
                      [[[-1.6569e-01,  1.3392e-01, -1.8564e-01],
                        [-5.6104e-02, -1.9228e-01,  1.2668e-01],
                        [ 2.2337e-01, -7.4634e-02, -1.5330e-01]],
              
                       [[-1.3344e-01, -2.6960e-01, -1.5580e-01],
                        [ 3.0235e-01, -1.5618e-01,  1.6963e-01],
                        [-2.3885e-01, -1.2401e-02,  2.3923e-01]]],
              
              
                      [[[ 1.1516e-01,  1.0318e-01, -1.0890e-01],
          